/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OkrsRouteImport } from './routes/okrs'
import { Route as HierarchyRouteImport } from './routes/hierarchy'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as BlockersRouteImport } from './routes/blockers'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AlignmentRouteImport } from './routes/alignment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OkrsRoute = OkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => rootRouteImport,
} as any)
const HierarchyRoute = HierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockersRoute = BlockersRouteImport.update({
  id: '/blockers',
  path: '/blockers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignmentRoute = AlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/auth/__layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/blockers': typeof BlockersRoute
  '/employees': typeof EmployeesRoute
  '/hierarchy': typeof HierarchyRoute
  '/okrs': typeof OkrsRoute
  '/permissions': typeof PermissionsRoute
  '/progress': typeof ProgressRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/blockers': typeof BlockersRoute
  '/employees': typeof EmployeesRoute
  '/hierarchy': typeof HierarchyRoute
  '/okrs': typeof OkrsRoute
  '/permissions': typeof PermissionsRoute
  '/progress': typeof ProgressRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/blockers': typeof BlockersRoute
  '/employees': typeof EmployeesRoute
  '/hierarchy': typeof HierarchyRoute
  '/okrs': typeof OkrsRoute
  '/permissions': typeof PermissionsRoute
  '/progress': typeof ProgressRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alignment'
    | '/approvals'
    | '/audit-logs'
    | '/blockers'
    | '/employees'
    | '/hierarchy'
    | '/okrs'
    | '/permissions'
    | '/progress'
    | '/reviews'
    | '/settings'
    | '/teams'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alignment'
    | '/approvals'
    | '/audit-logs'
    | '/blockers'
    | '/employees'
    | '/hierarchy'
    | '/okrs'
    | '/permissions'
    | '/progress'
    | '/reviews'
    | '/settings'
    | '/teams'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/alignment'
    | '/approvals'
    | '/audit-logs'
    | '/blockers'
    | '/employees'
    | '/hierarchy'
    | '/okrs'
    | '/permissions'
    | '/progress'
    | '/reviews'
    | '/settings'
    | '/teams'
    | '/auth/__layout'
    | '/auth/login'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignmentRoute: typeof AlignmentRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BlockersRoute: typeof BlockersRoute
  EmployeesRoute: typeof EmployeesRoute
  HierarchyRoute: typeof HierarchyRoute
  OkrsRoute: typeof OkrsRoute
  PermissionsRoute: typeof PermissionsRoute
  ProgressRoute: typeof ProgressRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okrs': {
      id: '/okrs'
      path: '/okrs'
      fullPath: '/okrs'
      preLoaderRoute: typeof OkrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hierarchy': {
      id: '/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof HierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blockers': {
      id: '/blockers'
      path: '/blockers'
      fullPath: '/blockers'
      preLoaderRoute: typeof BlockersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alignment': {
      id: '/alignment'
      path: '/alignment'
      fullPath: '/alignment'
      preLoaderRoute: typeof AlignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignmentRoute: AlignmentRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BlockersRoute: BlockersRoute,
  EmployeesRoute: EmployeesRoute,
  HierarchyRoute: HierarchyRoute,
  OkrsRoute: OkrsRoute,
  PermissionsRoute: PermissionsRoute,
  ProgressRoute: ProgressRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  Auth_layoutRoute: Auth_layoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
